server:
  host: "0.0.0.0"
  port: "9090"
  mode: "debug"
  rootPath: "/api/v1"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "password"
  dbname: "goframex"
  schema: "public"
  sslmode: "disable"
  debug: true
  driver: "postgres"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: 3600

cache:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

logger:
  level: "info"
  timestamp_format: "2006-01-02 15:04:05"
  pattern: "%timestamp% | %level% | %requestId% | %file%:%line% | %function% | %message%"

external:
  user-client:
    url: "https://jsonplaceholder.typicode.com"
    timeout: "30s"
    retry_count: 3
    retry_wait: "1s"
    headers:
      "Content-Type": "application/json"
      "Accept": "application/json"
    debug: true